Upgrade to zetasql-2024-03-01 and bump deps
GoogleCloudPlatform/zetasql-toolkit pull request #33
Opened 2024-04-19 07:39 UTC by hamnis

Trying to move this forward by upgrading dependencies

2024-05-05 17:03 UTC, ppaglilla requested changes
Thanks for contributing this! I requested a couple of small changes.

Once we merge this, I'll immediately release v0.5.0. It has been a long time coming 😅.

2024-05-05 17:03 UTC, ppaglilla commented on zetasql-toolkit-bigquery/src/main/java/com/google/zetasql/toolkit/options/BigQueryLanguageOptions.java
> +                        LanguageFeature.FEATURE_V_1_4_BARE_ARRAY_ACCESS,
We should not enable all version 1.4 language features here, only those that BigQuery has. For this PR I'd only add the following, which are the ones I'm absolutely sure BigQuery supports.

This list misses some features which are supported for sure, feel free to add any that you know of. We should closely look at each one and enable them accordingly, but I'd keep that to a separate PR. 

* `FEATURE_V_1_4_ARRAY_AGGREGATION_FUNCTIONS`
* `FEATURE_V_1_4_REMOTE_MODEL`
* `FEATURE_V_1_4_GROUPING_BUILTIN`
* `FEATURE_V_1_4_GROUPING_SETS`
* `FEATURE_V_1_4_GROUP_BY_ALL`

2024-05-06 00:10 UTC, merged

2024-05-06 00:11 UTC, ppaglilla commented
I took the liberty of applying the couple of changes I requested myself and merging. I hope that's not an issue. Thanks again for the contribution!

I should be able to release 0.5.0 with these changes shortly.

2024-05-06 05:34 UTC, hamnis commented
Great. I was just heading in to work now to get this done, so this is perfect. Thanks a lot